Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/tabs.json")
Tracker:AddLayouts("layouts/devilarms.json")
Tracker:AddLayouts("layouts/guns.json")
Tracker:AddLayouts("layouts/settings.json")
Tracker:AddLayouts("layouts/styles.json")
Tracker:AddLayouts("layouts/progressive_items.json")
Tracker:AddLayouts("layouts/combat_items.json")

Tracker:AddLayouts("layouts/assignment_grid_order.json")
Tracker:AddLayouts("layouts/mission_assignments.json")
Tracker:AddLayouts("layouts/mission_keyitems.json")
Tracker:AddLayouts("layouts/missions.json")

Tracker:AddLayouts("layouts/broadcast.json")
