Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/tabs.json")
Tracker:AddLayouts("layouts/devilarms.json")
Tracker:AddLayouts("layouts/guns.json")
Tracker:AddLayouts("layouts/styles.json")
Tracker:AddLayouts("layouts/shopitems.json")

Tracker:AddLayouts("layouts/missions_keyitems.json")
Tracker:AddLayouts("layouts/mission19.json")
Tracker:AddLayouts("layouts/mission16.json")
Tracker:AddLayouts("layouts/mission15.json")
Tracker:AddLayouts("layouts/mission13.json")
Tracker:AddLayouts("layouts/mission12.json")
Tracker:AddLayouts("layouts/mission11.json")
Tracker:AddLayouts("layouts/mission10.json")
Tracker:AddLayouts("layouts/mission9.json")
Tracker:AddLayouts("layouts/mission8.json")
Tracker:AddLayouts("layouts/mission7.json")
Tracker:AddLayouts("layouts/mission6.json")
Tracker:AddLayouts("layouts/mission5.json")

Tracker:AddLayouts("layouts/missions.json")

Tracker:AddLayouts("layouts/broadcast.json")
